# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ytools}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe McArthur"]
  s.date = %q{2011-02-12}
  s.description = %q{Installs the ypath tool for reading YAML files using an XPath-like syntax.  Installs the ytemplates tool for writing ERB templates using YAML files as the template binding object.}
  s.email = ["madeonamac@gmail.com"]
  s.executables = ["ypath", "ytemplates"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "bin/ypath",
    "bin/ytemplates",
    "lib/VERSION",
    "lib/ytools/basecli.rb",
    "lib/ytools/errors.rb",
    "lib/ytools/path/cli.rb",
    "lib/ytools/path/examples.txt",
    "lib/ytools/path/executor.rb",
    "lib/ytools/path/lexer.rb",
    "lib/ytools/path/parser.rb",
    "lib/ytools/path/selectors.rb",
    "lib/ytools/templates/cli.rb",
    "lib/ytools/templates/examples.txt",
    "lib/ytools/templates/executor.rb",
    "lib/ytools/templates/yaml_object.rb",
    "lib/ytools/version.rb",
    "lib/ytools/yaml_object.rb",
    "lib/ytools/yreader.rb",
    "spec/helpers.rb",
    "spec/path/executor_spec.rb",
    "spec/path/lexer_spec.rb",
    "spec/path/parser_spec.rb",
    "spec/path/selectors_spec.rb",
    "spec/path/yamls/1.yml",
    "spec/path/yamls/2.yml",
    "spec/path/yamls/3.yml",
    "spec/path/yamls/4.yml",
    "spec/path/yamls/5.yml",
    "spec/path/yamls/6.yml",
    "spec/yaml_object_spec.rb"
  ]
  s.homepage = %q{http://github.com/gabemc/ytools}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{For reading or writing configuration files using YAML.}
  s.test_files = [
    "spec/helpers.rb",
    "spec/path/executor_spec.rb",
    "spec/path/lexer_spec.rb",
    "spec/path/parser_spec.rb",
    "spec/path/selectors_spec.rb",
    "spec/yaml_object_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.5"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.5"])
  end
end

